[package]
publish = false
name = "search-index"
version = "0.1.0"
edition = "2021"

[lib]
name = "search_index"
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
rayon = "1.10"
rand = "0.8"
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py310", "anyhow"] }
log = "0.4"
pyo3-log = "0.12"
itertools = "0.13"
memmap2 = "0.9"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.3"
any_ascii = "0.3"
ordered-float = "4.5"

[profile.release]
lto = true
codegen-units = 1
strip = true
